version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - php
  php:
    build: ./docker/php
    volumes:
      - .:/var/www/html
    links:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: laravel
    ports:
      - "3307:3306"
